### ISSUE TITLE
0.5.7 compatibility with VTTA modules

### ISSUE THREAD

**Issue by Norc** [Stryxin/dnd5edark-foundryvtt#1]
With just VTTA Party active and dnd5E dark mode enabled, VTTA Party displays correctly. However, when the VTtA Beyond Integration module is ALSO enabled, for whatever reason the VTTA Party Module's banded rows are not properly darkened:

![image](https://user-images.githubusercontent.com/64667579/82134098-db2f1680-97c1-11ea-82e1-44e77502e0bc.png)

Foundry 0.5.7, DND5E DarkMode version 2.0.2, VTTA Party Overview 2.2.0, VTTA Beyond Integration 2.2.14. Only these modules were enabled.

**Comment by Stryxin** [comment]
Fixed in 2.0.3
