### ISSUE TITLE
Inventory item names and spell names are the same color as the background making them appear invisible.

### ISSUE THREAD

**Issue by 00zim00** [Stryxin/dnd5edark-foundryvtt#10]
![dark Mode issue](https://user-images.githubusercontent.com/67153208/95646005-cc9a2080-0b0f-11eb-84b9-a9e798add1ce.jpg)

It has been working for a long time however a few days ago all our sheets font have changed to black for named assets, (items, spells)

They font is their but it makes it appear invisible.

Have disabled all other modules and it still happens to all of us.

If you need any other information let me know. Thanks.

**Comment by Lazytron** [comment]
also happening for me after .7.5/.98  update (from .6.6/.96)

**Comment by AceAckbar** [comment]
Same issue as of yesterday. Was working fine since I started using it. As soon as I updated yesterday: *bam*.  Text appearing as above. Hoping this can get fixed soon, because I love this sheet and would hate to change it :c

**Comment by TheGiddyLimit** [comment]
Fixed as of 2.1.0.
