### ISSUE TITLE
2.1.2 collides with Token Action HUD .8.1

### ISSUE THREAD

**Issue by Lazytron** [Stryxin/dnd5edark-foundryvtt#16]
in Foundrywide dark mode: 
![image](https://user-images.githubusercontent.com/32400728/97129278-7a125400-170c-11eb-9139-a314432875d4.png)

xposted [here](https://github.com/espositos/fvtt-tokenactionhud/issues/85)

**Comment by espositos** [comment]
Is there something I can do for the HUD to make it compatible with this?

**Comment by LorduFreeman** [comment]
Happens because the button definitions are changed when in dark mode. As a quick fix, add these lines at the end of your dark-mode.css file
```
/* Fix for Token Action Hud */
.dark-mode .tah-title-button {
    background: rgba(0, 0, 0, 0.7);
}
/* endregion */
```

**Comment by LorduFreeman** [comment]
I've investigated, the error comes from this:
Line 58: 	background: var(--5edark-rgb-bg-black)c4;

the variable + transparency (c4) does not get concatenated properly leading to transparent buttons and affecting Token Action HUD as well.
