### ISSUE TITLE
No Longer Playing Nicely with Token Health

### ISSUE THREAD

**Issue by Dumbhuman** [Stryxin/dnd5edark-foundryvtt#19]
I used to have both modules running with no issues, but currently on Foundry core 0.6.6 and DnD5e 0.9.8 using the latest release of both DnD5e Dark Mode and Token Health, I can't see numbers in the health field unless I select them.

![darkheal](https://user-images.githubusercontent.com/63615591/98304438-d713d280-1f74-11eb-8b5e-58aee32e9c6a.gif)

**Comment by NutritiousCookie** [comment]
Or the normal token config menu

![ezgif-3-0d95bf072a6b](https://user-images.githubusercontent.com/30578022/98345689-9ea6df80-1fda-11eb-90b8-28be5f519d6c.gif)
