### ISSUE TITLE
Text isnt white on ability scores or personality traits page. alot of white text is missing.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [Stryxin/dnd5edark-foundryvtt#20]
im using 0.7.7 and the white text on ability scores aswell as the personality traits isnt showing. making it hard for players to see. i cannot use your module until its fixed. i would like to :)

**Comment by deraviin** [comment]
Have to say that yes some text is not showing up as white. Would still love to use this and will still BE using it but yeah having to copy paste the monsters to see their AC is frustrating lol
