### ISSUE TITLE
Zip file contains outdated version or wrong module.json

### ISSUE THREAD

**Issue by FaeyUmbrea** [Stryxin/dnd5edark-foundryvtt#21]
The file that is downloaded via the module.json contains a module.json declaring itself as v2.1.2 instead of v2.2.0

**Comment by TheGiddyLimit** [comment]
I'm well aware; v2.2.0 is as-yet unreleased

**Comment by FaeyUmbrea** [comment]
Ah well, then you should change the module.json the updater is referencing because that is suggesting 2.2.0 does exist and constantly tries to download it when you check for updates in foundry.

**Comment by TheGiddyLimit** [comment]
It's on my to-do list
