### ISSUE TITLE
White text missing on Token Configuration tabs

### ISSUE THREAD

**Issue by erpangilinan** [Stryxin/dnd5edark-foundryvtt#23]
On Foundry 0.7.9 and D&D5e 1.2.0 and fillable texts on Token Configuration screen for Image tab (Width & Height), Position tab (X-Coordinate, Y-Coordinate, Elevation, Rotation),  and Vision tab (Dim Vision, Bright Vision, Sight Angle, Dim Light Radius,  Bright Light Radius, Emission Angle).

The issue doesnt seem to affect drop down menus or the tint color hex value.

The issue also persists no matter what sheet style is used, for both NPC and Player sheets

**Comment by TheGiddyLimit** [comment]
Can't reproduce this. What version of dark are you using?

**Comment by erpangilinan** [comment]
Updated to 2.2.3 and this bug is gone now. Thanks.
