### ISSUE TITLE
Various Visual Bugs

### ISSUE THREAD

**Issue by revilowaldow** [Stryxin/dnd5edark-foundryvtt#24]
### General Issues
- Inline Dice button icon excurses from boundary, button has no fill colour
![image](https://user-images.githubusercontent.com/52298102/103928344-9a4e8e00-5113-11eb-8655-82c976ae8069.png)

- Roll Mode Drop-down is not themed for dark mode (text themed, background not - poor readability)
![image](https://user-images.githubusercontent.com/52298102/103928396-b0f4e500-5113-11eb-9c30-d198a1e5e60a.png)

- Some Key Icons in the Controls Reference Page are not themed,
![image](https://user-images.githubusercontent.com/52298102/103928777-3c6e7600-5114-11eb-8dd7-3772305954f4.png)
![image](https://user-images.githubusercontent.com/52298102/103928798-41cbc080-5114-11eb-95b9-12df861b1ee1.png)
![image](https://user-images.githubusercontent.com/52298102/103928819-46907480-5114-11eb-97e3-de1023140745.png)

- Text nearly impossible to read in player configuration boxes
![image](https://user-images.githubusercontent.com/52298102/103930599-e7802f00-5116-11eb-8193-c030e0174f4b.png)

- Colour picker UI not themed (this one might be fair, but it is a solid block of white)
![image](https://user-images.githubusercontent.com/52298102/103930745-22826280-5117-11eb-93a4-ba1f39b0d93a.png)

### Plutonium Specific Issues
- Plutonium Charactermancer not yet supported in dark mode, please bear in mind during development
     Might be as simple as setting it to use the "dark parchment" asset and changing the dropdown fill colours

- When using plutonium module drag&drop confirmation box has no fill colour
![image](https://user-images.githubusercontent.com/52298102/103928475-cbc75980-5113-11eb-886a-95b076860111.png)

- When using Plutonium, ... dropdown menu has no fill colour and is offset from origin location
![image](https://user-images.githubusercontent.com/52298102/103928553-ea2d5500-5113-11eb-99f3-e05114b7b63e.png) ![image](https://user-images.githubusercontent.com/52298102/103929240-eea63d80-5114-11eb-854d-0c6037c591e5.png)

- Tools menu has no fill
![image](https://user-images.githubusercontent.com/52298102/103930344-7b9dc680-5116-11eb-8ed9-1818ee36ce30.png)

- Plutonium Filter Page has no fill
![image](https://user-images.githubusercontent.com/52298102/103929581-6d02df80-5115-11eb-9cf9-8c149fca31dc.png)

**Comment by TheGiddyLimit** [comment]
Was unable to repro this:
> Inline Dice button icon excurses from boundary, button has no fill colour

Aside from that, and the un-fixable colour picker, the rest should now be fixed. Thanks again.

**Comment by revilowaldow** [comment]
Repro steps:
New world with only modules: 
- Plutonium ![image](https://user-images.githubusercontent.com/52298102/104105904-85a3fe80-52a9-11eb-9aa4-a589f1f46a15.png)
- D&D5E Dark Mode ![image](https://user-images.githubusercontent.com/52298102/104105911-93f21a80-52a9-11eb-8234-0a9c35d37a2c.png)

Use characetermancer to import Artificer Armorer with minimum 3 levels forth of features.
Check "Armor Model" feature in sheet for example. 
![image](https://user-images.githubusercontent.com/52298102/104105974-0f53cc00-52aa-11eb-86dc-f31535b37435.png)
