### ISSUE TITLE
Module Settings option missing: Activate Foundry wide Dark mode?

### ISSUE THREAD

**Issue by wlafrance** [Stryxin/dnd5edark-foundryvtt#3]
After upgrading from a Patreon version to a paid version my Dark Mode Module has seemed to stop working.  I can enable the module, but when I open the Configure Game Settings > Module Settings
I do **not see** the D&D5E Dark Mode option: Activate Foundry Wide Dark Mode? [check box ]

This is a video recording my steps to reproduce...
https://drive.google.com/open?id=1WtQjOx9KquQL0UNTJ-suW3xYUCM75lNd

**Comment by Stryxin** [comment]
Update your D&D 5e System module, there were some changes in 0.9 so the older version is no longer compatible

**Comment by wlafrance** [comment]
That was the issue.  Thanks
