### ISSUE TITLE
Visual bugs log

### ISSUE THREAD

**Issue by revilowaldow** [Stryxin/dnd5edark-foundryvtt#31]
Poor visibility in charactermancer dropdowns. (Thank you for recent update, it looks great!)

![image](https://user-images.githubusercontent.com/52298102/110362550-50155a80-8039-11eb-85f9-9801d4c5bca9.png)
![image](https://user-images.githubusercontent.com/52298102/110362553-50adf100-8039-11eb-878c-ca7855d91713.png)

**Comment by revilowaldow** [comment]
Filters do not show red/blue colouring when selected/blocked
https://imgur.com/i5LpgeC

**Comment by revilowaldow** [comment]
Inline import options are not dark moded:
![image](https://user-images.githubusercontent.com/52298102/111038412-a4954d00-8420-11eb-85af-2940398c6fb5.png)

**Comment by TheGiddyLimit** [comment]
Should all be fixed in 3.0.1

**Comment by revilowaldow** [comment]
> Should all be fixed in 3.0.1

Sorry to ping you, did 3.0.1 actually get released? It's not updating automatically in Foundry?

**Comment by TheGiddyLimit** [comment]
Looks like I didn't bump the `module.json` version, which I thought I had scripted so I didn't have to remember 🤔 
Should now be fixed? If not, it'll all come out in the wash next release.

**Comment by revilowaldow** [comment]
Doesn't seem to have updated in foundry with a delete and reinstall. I'll give it another try later in case it's cached somewhere but no worries if not. I'll just try and find another bug for you to fix to get it bumped earlier ;P
