### ISSUE TITLE
Visual Bug Log the Second

### ISSUE THREAD

**Issue by revilowaldow** [Stryxin/dnd5edark-foundryvtt#33]
DAE Effect Headings Unreadable
![image](https://user-images.githubusercontent.com/52298102/111924124-bdde6f00-8a9a-11eb-871d-9c1635b9b4c5.png)

CUB Module has un-themed dropdown
![image](https://user-images.githubusercontent.com/52298102/111924136-cfc01200-8a9a-11eb-9e82-63b07dcef61c.png)

Link adding pop-up is harsh white in foundry-wide dark mode
![image](https://user-images.githubusercontent.com/52298102/111924143-e1091e80-8a9a-11eb-9ce0-4b09c45cf2a4.png)

**Comment by revilowaldow** [comment]
### Combat Tracker dropdown text partially themed
![image](https://user-images.githubusercontent.com/52298102/112012683-50c1ec80-8b21-11eb-8fb0-33e74cd8180e.png)

### "Create New X" dropdown text not themed

Actor
![image](https://user-images.githubusercontent.com/52298102/112012162-de510c80-8b20-11eb-9b63-6764246a25f2.png)
Scene 
![image](https://user-images.githubusercontent.com/52298102/112012244-f1fc7300-8b20-11eb-80a6-4eae76528bb8.png)
Item 
![image](https://user-images.githubusercontent.com/52298102/112012302-fd4f9e80-8b20-11eb-94b5-07b89038eef5.png)
Journal 
![image](https://user-images.githubusercontent.com/52298102/112012499-27a15c00-8b21-11eb-996f-fe3045711592.png)
Table
![image](https://user-images.githubusercontent.com/52298102/112012521-2cfea680-8b21-11eb-9f1d-816a042f7b7a.png)
Compendium
![image](https://user-images.githubusercontent.com/52298102/112012599-3be55900-8b21-11eb-8f50-88c661ef21f5.png)
Macro
![image](https://user-images.githubusercontent.com/52298102/112013274-d6459c80-8b21-11eb-9dec-b5c9a4968142.png)

Roll type: 
![image](https://user-images.githubusercontent.com/52298102/112012841-6d5e2480-8b21-11eb-923e-a5c427043222.png)

Polyglot Language 
![image](https://user-images.githubusercontent.com/52298102/112012871-74853280-8b21-11eb-98b7-f0f831179778.png)

Sheet type
![image](https://user-images.githubusercontent.com/52298102/112013004-97174b80-8b21-11eb-9898-06f8345403fc.png)

...just most dropdowns honestly

**Comment by revilowaldow** [comment]
Titles not readable in Item Effects Tab when opened from Items Sidebar
![image](https://user-images.githubusercontent.com/52298102/114303859-1a481380-9ac8-11eb-8179-537a114e9366.png)

**Comment by 00zim00** [comment]
If it helps, it seems to be anything with a Drop Down menu across all sheets and menus. So its probably just one value that needs to be fixed for all drop down menus.

**Comment by NutritiousCookie** [comment]
[Item Containers](https://gitlab.com/tposney/itemcollection) seems to have a similar issue to Item Effects Tab

![image](https://user-images.githubusercontent.com/30578022/133981861-dd1cdf23-e202-4675-9fd0-07e25817d31d.png)
