### ISSUE TITLE
Compatibility with Polyglot and DND5e UI

### ISSUE THREAD

**Issue by TheTercept** [Stryxin/dnd5edark-foundryvtt#7]
When Dark Mode everywhere is enabled and using the DND5e UI module with polyglot the text box and language selector are unreadable.

![image](https://user-images.githubusercontent.com/66691804/86927443-5a293700-c101-11ea-9f09-e7726a53fa0f.png)

**Comment by Stryxin** [comment]
Install Custom CSS module, add these 3 custom rules:

`#chat-message { color: #000000 !important; }`

`.sidebar-tab .directory-header .header-search input { color: #BFBFBF !important; }`

`.polyglot-lang-select select {  color: #000000 !important; }`
