### ISSUE TITLE
Error on closing actor sheet in a locked compendium (0.6.5)

### ISSUE THREAD

**Issue by DeadlyArtist** [Stryxin/dnd5edark-foundryvtt#8]
"You cannot modify content in this compendium because it is locked"

Only BetterNPCSheet5e activated, this error is shown each time an actor sheet in a locked compendium is closed.

Updating DnD5e module allowed the window to close even with error, but it's still too annoying to see the error every time, especially when this sheet is by far best.

**Comment by TheGiddyLimit** [comment]
The Better NPC Sheet 5e module produces this error with this module disabled. Please report the issue there instead.
